services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB:   ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"

  php-fpm:
    build:
      context: .
      dockerfile: php/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:ro
    depends_on:
      - php-fpm

volumes:
  db_data: